import {FormEvent,useEffect,useState} from 'react';import {Link,useParams,useSearchParams} from 'react-router';import {ArrowRight,BookOpen,FileText,History,Landmark,Library,MessagesSquare,Search,ShieldCheck,Vote} from 'lucide-react';import {discussionCategories,proposalTabs,workflow} from './data/constitution';import {ConstitutionChapter,constitutionSources,loadArticleByNumber,loadChapters,searchConstitution} from './services/constitution';
const actions=[['/katiba','Soma Katiba','Vinjari sura, sehemu, ibara na vifungu.'],['/proposed','Katiba Inayopendekezwa','Soma rasimu, linganisha mapendekezo na fuatilia mabadiliko.'],['/submit','Toa Pendekezo','Wasilisha maoni yako kwa muundo unaoweza kufuatiliwa.'],['/polls','Piga Kura','Shiriki katika hatua mbalimbali za kura za kikatiba.'],['/discussions','Majadiliano','Jadili ibara, mada na tafsiri kwa uwazi.'],['/history','Historia ya Katiba','Fuatilia maendeleo ya Katiba na nyaraka muhimu.']];
export function HomePage(){return <><section className="hero"><div className="heroCopy"><div className="eyebrow">SOMA · JADILI · PENDEKEZA · PIGA KURA</div><h1>Ifahamu Katiba.<br/><span>Sauti yako ihesabike.</span></h1><p>Jukwaa la kidijitali la Watanzania kusoma Katiba, kujadili ibara, kutoa mapendekezo, kushiriki kura za maoni na kufuatilia mchakato wa Katiba Inayopendekezwa.</p><div className="heroButtons"><Link className="primary linkBtn" to="/katiba">Soma Katiba <ArrowRight size={18}/></Link><Link className="secondary linkBtn" to="/submit">Shiriki Maoni</Link></div><Link to="/search" className="searchBox linkSearch"><Search/><span>Tafuta ibara, neno, au mada...</span></Link></div><div className="heroPanel"><div className="seal"><Landmark size={44}/></div><div className="document"><span>JAMHURI YA MUUNGANO WA TANZANIA</span><h3>KATIBA</h3><p>Maarifa ya kikatiba yaliyoandaliwa kwa usomaji, utafutaji na ushiriki wa wananchi.</p></div><div className="notice"><ShieldCheck/><span>Maandishi rasmi hayatabadilishwa na mapendekezo ya wananchi.</span></div></div></section><section className="section"><div className="sectionHead"><div><span className="kicker">ANZA HAPA</span><h2>Shiriki katika mchakato</h2></div></div><div className="cards">{actions.map(([to,title,body],i)=>{const I=[BookOpen,FileText,MessagesSquare,Vote,MessagesSquare,History][i];return <Link className="card cardLink" to={to} key={title}><div className="icon"><I/></div><h3>{title}</h3><p>{body}</p><span>Fungua →</span></Link>})}</div></section><Governance/></>}
export function LibraryPage(){
 const {documentId}=useParams();const source=constitutionSources.find(s=>s.id===documentId);const [chapters,setChapters]=useState<ConstitutionChapter[]>([]);const [loading,setLoading]=useState(Boolean(source));
 useEffect(()=>{let live=true;if(!source){setLoading(false);return}setLoading(true);loadChapters(source.id).then(x=>{if(live){setChapters(x);setLoading(false)}});return()=>{live=false}},[source?.id]);
 if(!source)return <Page title="Maktaba ya Katiba" kicker="KATIBA"><p className="lead">Chagua hati. Maandishi yanasomwa moja kwa moja kutoka kwenye faili za asili zilizopo kwenye mfumo.</p><div className="docGrid">{constitutionSources.map(d=><Link className="docCard docLink" key={d.id} to={'/katiba/'+d.id}><div className="docTop"><BookOpen/><span>{d.family==='official'?'KATIBA':'RASIMU'}</span></div><h3>{d.title}</h3><p>{d.family==='official'?'Hati ya Katiba katika maktaba ya mfumo.':'Rasimu imehifadhiwa tofauti na Katiba rasmi.'}</p><span className="textLink">Fungua sura na ibara →</span></Link>)}</div></Page>;
 return <Page title={source.title} kicker={source.family==='official'?'KATIBA':'RASIMU'}><div className="readerTools"><Link to="/katiba">← Maktaba</Link><Link to={'/search?document='+source.id}><Search size={16}/> Tafuta ndani ya hati</Link></div>{loading?<Empty text="Inapakia sura kutoka faili za asili..."/>:<div className="chapterList">{chapters.map(ch=><details className="chapterCard" key={ch.sura}><summary><div><span>SURA {ch.chapterNumber}</span><h3>{ch.jina}</h3><small>{ch.ibara.length} ibara</small></div><ArrowRight/></summary>{ch.sehemu?.length>0&&<div className="chapterParts">{ch.sehemu.map(x=><span key={x}>{x}</span>)}</div>}<div className="articleLinks">{ch.ibara.map(file=>{const n=file.replace(/^Ibara\s+/i,'').replace(/\.json$/i,'');return <Link key={file} to={'/katiba/'+source.id+'/'+encodeURIComponent(n)}>Ibara {n}</Link>})}</div></details>)}</div>}</Page>
}
export function ArticlePage(){
 const {documentId,articleId}=useParams();const source=constitutionSources.find(s=>s.id===documentId);const [record,setRecord]=useState<Awaited<ReturnType<typeof loadArticleByNumber>>>();const [loading,setLoading]=useState(true);
 useEffect(()=>{let live=true;setLoading(true);if(documentId&&articleId)loadArticleByNumber(documentId,decodeURIComponent(articleId)).then(x=>{if(live){setRecord(x);setLoading(false)}});else setLoading(false);return()=>{live=false}},[documentId,articleId]);
 if(loading)return <Page title="Inapakia ibara..." kicker={source?.title||'KATIBA'}><Empty text="Inasoma faili halisi ya ibara..."/></Page>;
 if(!record)return <Page title="Ibara haijapatikana" kicker={source?.title||'KATIBA'}><Empty text="Ibara hii haikupatikana katika faili za chanzo."/></Page>;
 const {article,chapter}=record;const idx=chapter.ibara.findIndex(f=>f===record.fileName);const number=(f?:string)=>f?.replace(/^Ibara\s+/i,'').replace(/\.json$/i,'');
 return <Page title={'Ibara '+article.ibara} kicker={source?.title||'KATIBA'}><div className="breadcrumbs"><Link to={'/katiba/'+documentId}>{chapter.sura}</Link><span>›</span><span>{article.sehemu||chapter.jina}</span></div><article className="articleReader"><header><div><span className="articleNumber">IBARA {article.ibara}</span><h2>{article.jina}</h2></div><span className={'status '+article.chanzo.verificationStatus}>{article.chanzo.verificationStatus}</span></header>{article.vifungu?.length?<div className="clauses">{article.vifungu.map((v,i)=><p key={i}>{v}</p>)}</div>:<p className="articleText">{article.maudhui}</p>}<footer className="sourceLine"><span>Chanzo: {article.chanzo.sourceLocator}</span><span>{record.fileName}</span></footer></article><div className="articleNav">{idx>0?<Link to={'/katiba/'+documentId+'/'+encodeURIComponent(number(chapter.ibara[idx-1])!)}>← Ibara {number(chapter.ibara[idx-1])}</Link>:<span/>}{idx<chapter.ibara.length-1&&<Link to={'/katiba/'+documentId+'/'+encodeURIComponent(number(chapter.ibara[idx+1])!)}>Ibara {number(chapter.ibara[idx+1])} →</Link>}</div><div className="workspaceTabs">{['Soma','Ufafanuzi','Majadiliano','Mapendekezo','Kura','Marejeo'].map(x=><button key={x}>{x}</button>)}</div></Page>
}
export function SearchPage(){
 const [params,setParams]=useSearchParams();const [q,setQ]=useState(params.get('q')||'');const docId=params.get('document')||undefined;const [results,setResults]=useState<Awaited<ReturnType<typeof searchConstitution>>>([]);const [searched,setSearched]=useState(false);const [loading,setLoading]=useState(false);
 async function run(term:string){setLoading(true);const x=await searchConstitution(term,docId);setResults(x);setSearched(true);setLoading(false)}
 useEffect(()=>{const initial=params.get('q');if(initial)run(initial)},[docId]);
 function submit(e:FormEvent){e.preventDefault();setParams(p=>{if(q)p.set('q',q);else p.delete('q');if(docId)p.set('document',docId);return p});run(q)}
 return <Page title="Tafuta Katiba" kicker="UTAFUTAJI"><form className="bigSearch" onSubmit={submit}><Search/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Tafuta ibara, neno, au mada..."/><button>Tafuta</button></form>{docId&&<p className="searchScope">Inatafuta ndani ya: {constitutionSources.find(s=>s.id===docId)?.title}</p>}{loading?<Empty text="Inatafuta kwenye faili za Katiba..."/>:results.length?<div className="resultList">{results.map(({source,article})=><Link to={'/katiba/'+source.id+'/'+encodeURIComponent(String(article.ibara))} key={source.id+'-'+article.ibara}><b>Ibara {article.ibara}</b><span><strong>{article.jina}</strong><small>{source.title} · {article.sura}</small></span></Link>)}</div>:<Empty text={searched?'Hakuna matokeo yaliyopatikana.':'Andika neno, mada au namba ya ibara.'}/>}</Page>
}
export function ProposedPage(){return <Page title="Katiba Inayopendekezwa" kicker="RASIMU"><p className="lead">Workspace ya kufuatilia rasimu na mapendekezo bila kuchanganya maandishi rasmi ya Katiba na maandishi yanayopendekezwa.</p><div className="pills">{proposalTabs.map(x=><button key={x}>{x}</button>)}</div><div className="split workspace"><div className="panel"><h3>Rasimu ya sasa</h3><Empty text="Hakuna rasimu iliyochaguliwa. Rasimu halisi kutoka dataset itaorodheshwa hapa."/ ></div><aside className="process"><h3>Mchakato wa uidhinishaji</h3>{workflow.map((x,i)=><div className="step" key={x}><b>{i+1}</b><span>{x}</span></div>)}</aside></div><div className="notice wide"><ShieldCheck/><span>Kura hazikubali ibara moja kwa moja. Mapitio ya kisheria na uamuzi wa kamati hubaki hatua tofauti.</span></div></Page>}
export function PollsPage(){return <Page title="Kura za Kikatiba" kicker="KURA"><p className="lead">Kura za ushauri zinaweza kupitia hatua nne: uthibitisho wa tatizo, mwelekeo wa sera, wording ya ibara, na approval for draft.</p><Empty text="Hakuna kura hai iliyopakiwa kwenye web app kwa sasa."/ ><div className="notice wide"><Vote/><span>Matokeo ya kura hayatawasilishwa kama uwakilishi wa kitaifa bila msingi wa kufanya hivyo, na kura haziidhinishi rasimu moja kwa moja.</span></div></Page>}
export function DiscussionsPage(){return <Page title="Majadiliano ya Katiba" kicker="JUKWAA"><p className="lead">Majadiliano yanaweza kuunganishwa moja kwa moja na ibara au mada.</p><div className="topicGrid">{discussionCategories.map(x=><article className="miniCard" key={x}><MessagesSquare/><h3>{x}</h3><p>Fungua mijadala na majibu yanayohusiana na mada hii.</p></article>)}</div></Page>}
export function HistoryPage(){return <Page title="Historia ya Katiba" kicker="HISTORIA"><p className="lead">Timeline ya nyaraka na hatua za kikatiba. Taarifa ambazo hazijathibitishwa zinapaswa kubaki na alama ya uhakiki.</p><div className="timeline">{['1961','1962','1964','1977','1984','2014–2015'].map((y,i)=><div className="timelineItem" key={y}><b>{y}</b><span>{['Uhuru na mpangilio wa mwanzo','Jamhuri','Muungano','Katiba ya Jamhuri ya Muungano','Katiba ya Zanzibar','Mchakato wa rasimu na mjadala'][i]}</span></div>)}</div></Page>}
export function ResourcesPage(){return <Page title="Maktaba ya Rasilimali" kicker="RASILIMALI"><p className="lead">Hati rasmi, marekebisho, rasimu, ripoti, nyaraka za elimu na hukumu zinaweza kusajiliwa hapa pamoja na source na verification status.</p><div className="pills">{['Original','Amendment','Draft','Report','Educational','Judgment'].map(x=><button key={x}>{x}</button>)}</div><Empty text="Orodha ya faili kutoka kwenye Katiba dataset itaunganishwa katika hatua ya import."/ ></Page>}
export function AccountPage(){return <Page title="Akaunti" kicker="UTAMBULISHO"><div className="panel narrow"><h3>Ingia / Jisajili</h3><p>Web architecture imeandaliwa kwa role-based access: Citizen, Verified Citizen, Legal Expert, Moderator, Drafting Committee na Administrator.</p><button className="primary">Endelea</button></div></Page>}
export function SubmissionPage(){const [sent,setSent]=useState(false);if(sent)return <Page title="Pendekezo limehifadhiwa" kicker="MCHANGO"><div className="notice wide"><ShieldCheck/><span>Demo ya web imepokea form locally tu. Backend submission service ndiyo itaunganisha validation, screening, duplicate detection, classification na clustering.</span></div></Page>;return <Page title="Wasilisha Pendekezo" kicker="MCHANGO WA MWANANCHI"><form className="proposalForm" onSubmit={e=>{e.preventDefault();setSent(true)}}><label>Kichwa<input required/></label><label>Mada<input required/></label><label>Ibara inayohusika<input/></label><label>Tatizo<textarea required/></label><label>Maneno unayopendekeza<textarea required/></label><label>Sababu<textarea required/></label><label>Ushahidi / chanzo<textarea/></label><label>Mkoa<input/></label><label className="check"><input type="checkbox"/> Wasilisha bila kuonyesha jina hadharani</label><button className="primary">Wasilisha Pendekezo</button></form></Page>}
function Page({title,kicker,children}:{title:string;kicker:string;children:React.ReactNode}){return <section className="section page"><span className="kicker">{kicker}</span><h1 className="pageTitle">{title}</h1>{children}</section>}
function Empty({text}:{text:string}){return <div className="empty"><Library/><p>{text}</p></div>}
function Governance(){return <section className="section governance"><span className="kicker">UAMINIFU WA MFUMO</span><h2>Mchakato unaofuatilika</h2><div className="govGrid"><article><ShieldCheck/><h3>Maandishi rasmi hayabadilishwi</h3><p>Mapendekezo na rasimu huhifadhiwa tofauti na maandishi rasmi.</p></article><article><History/><h3>Historia ya mabadiliko</h3><p>Mabadiliko, mapitio na maamuzi yanaweza kuhifadhiwa katika audit trail.</p></article><article><Library/><h3>Maoni tofauti yanahifadhiwa</h3><p>Mfumo umeundwa kuhifadhi mitazamo mbalimbali bila kuifanya kuwa msimamo rasmi.</p></article></div></section>}